apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata: 
       name: myapp
       labels:
         app: myapp
         type: front-end
    spec:
      containers:
        - image: dockerayush039/myfirstimage
          name: myapp
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      type: front-end
